FROM node:21-alpine3.18 
WORKDIR /app 
COPY package*.json ./
COPY tsconfig.json ./
COPY .npmrc ./ 
RUN npm install && npm install -g nodemon
COPY src ./src 
COPY tools ./tools
RUN ls -a
EXPOSE 4001
CMD ["npm", "run", "dev"]